# Generated by Django 5.0.2 on 2024-05-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='users',
            field=models.ManyToManyField(related_name='menu_items', to='coffee.user'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='time_to_serve',
            field=models.IntegerField(),
        ),
    ]
